services:
  registry-console:
    image: registry.ovh-1.moviik.com/registry-console:v2-multiarch-fixed-final
    container_name: registry-console
    # Remove ports mapping - Traefik will handle routing
    # ports:
    #   - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - registry-net
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.registry-console.rule=Host(`seu-dominio.com`)"  # Substitua pelo seu domínio real
      - "traefik.http.routers.registry-console.entrypoints=websecure"
      - "traefik.http.routers.registry-console.tls.certresolver=letsencrypt"
      - "traefik.http.services.registry-console.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"

  # Production profile with optimized settings for Traefik
  registry-console-prod:
    image: registry.ovh-1.moviik.com/registry-console:v2-multiarch-fixed-final
    container_name: registry-console-prod
    # Remove ports mapping - Traefik will handle routing
    # ports:
    #   - "3001:3000"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}
      REGISTRY_USERNAME: ${REGISTRY_USERNAME}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
      NODE_ENV: production
      DEFAULT_THEME: dark
      AUTO_REFRESH_INTERVAL: 600000
      CACHE_ENABLED: true
      CACHE_TTL: 900000
      NOTIFICATIONS_ENABLED: true
      SETTINGS_EXPORT_ENABLED: false
    restart: unless-stopped
    networks:
      - registry-net
      - traefik
    profiles:
      - production
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Traefik configuration for production
      - "traefik.enable=true"
      - "traefik.http.routers.registry-console-prod.rule=Host(`registry-prod.yourdomain.com`)"  # Altere para seu domínio
      - "traefik.http.routers.registry-console-prod.entrypoints=websecure"
      - "traefik.http.routers.registry-console-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.registry-console-prod.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"

  # Development profile with debug settings  
  registry-console-dev:
    build: .
    container_name: registry-console-dev
    ports:
      - "3002:3000"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}
      REGISTRY_USERNAME: ${REGISTRY_USERNAME}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
      NODE_ENV: development
      DEFAULT_THEME: light
      AUTO_REFRESH_INTERVAL: 60000
      CACHE_ENABLED: false
      NOTIFICATIONS_ENABLED: true
      SETTINGS_EXPORT_ENABLED: true
    restart: unless-stopped
    networks:
      - registry-net
    profiles:
      - development
    volumes:
      - ./public:/app/public:ro

networks:
  registry-net:
    driver: bridge
  traefik:
    external: true
