version: '3.8'

services:
  registry-console:
    build: .
    container_name: registry-console
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - registry-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/settings"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production profile with optimized settings
  registry-console-prod:
    build: .
    container_name: registry-console-prod
    ports:
      - "3001:3000"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}
      REGISTRY_USERNAME: ${REGISTRY_USERNAME}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
      NODE_ENV: production
      DEFAULT_THEME: dark
      AUTO_REFRESH_INTERVAL: 600000
      CACHE_ENABLED: true
      CACHE_TTL: 900000
      NOTIFICATIONS_ENABLED: true
      SETTINGS_EXPORT_ENABLED: false
    restart: unless-stopped
    networks:
      - registry-net
    profiles:
      - production

  # Development profile with debug settings  
  registry-console-dev:
    build: .
    container_name: registry-console-dev
    ports:
      - "3002:3000"
    environment:
      REGISTRY_URL: ${REGISTRY_URL}
      REGISTRY_USERNAME: ${REGISTRY_USERNAME}
      REGISTRY_PASSWORD: ${REGISTRY_PASSWORD}
      NODE_ENV: development
      DEFAULT_THEME: light
      AUTO_REFRESH_INTERVAL: 60000
      CACHE_ENABLED: false
      NOTIFICATIONS_ENABLED: true
      SETTINGS_EXPORT_ENABLED: true
    restart: unless-stopped
    networks:
      - registry-net
    profiles:
      - development
    volumes:
      - ./public:/app/public:ro

networks:
  registry-net:
    driver: bridge
