version: '3.8'

services:
  registry-ui:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - registry-net

networks:
  registry-net:
    driver: bridge
